/**
 * Curated lists for city and country dropdowns.
 * Single source of truth — used by extension, Discover, and API.
 */

export const COUNTRIES: { code: string; name: string }[] = [
  { code: 'RU', name: 'Russia' },
  { code: 'KZ', name: 'Kazakhstan' },
  { code: 'UA', name: 'Ukraine' },
  { code: 'BY', name: 'Belarus' },
  { code: 'US', name: 'United States' },
  { code: 'GB', name: 'United Kingdom' },
  { code: 'DE', name: 'Germany' },
  { code: 'FR', name: 'France' },
  { code: 'NL', name: 'Netherlands' },
  { code: 'PL', name: 'Poland' },
  { code: 'IT', name: 'Italy' },
  { code: 'ES', name: 'Spain' },
  { code: 'TR', name: 'Turkey' },
  { code: 'CA', name: 'Canada' },
  { code: 'AU', name: 'Australia' },
  { code: 'BR', name: 'Brazil' },
  { code: 'MX', name: 'Mexico' },
  { code: 'AR', name: 'Argentina' },
  { code: 'IN', name: 'India' },
  { code: 'CN', name: 'China' },
  { code: 'JP', name: 'Japan' },
  { code: 'KR', name: 'South Korea' },
  { code: 'SG', name: 'Singapore' },
  { code: 'ID', name: 'Indonesia' },
  { code: 'TH', name: 'Thailand' },
  { code: 'VN', name: 'Vietnam' },
  { code: 'PH', name: 'Philippines' },
  { code: 'MY', name: 'Malaysia' },
  { code: 'AE', name: 'United Arab Emirates' },
  { code: 'SA', name: 'Saudi Arabia' },
  { code: 'IL', name: 'Israel' },
  { code: 'EG', name: 'Egypt' },
  { code: 'ZA', name: 'South Africa' },
  { code: 'NG', name: 'Nigeria' },
  { code: 'KE', name: 'Kenya' },
  { code: 'CZ', name: 'Czech Republic' },
  { code: 'AT', name: 'Austria' },
  { code: 'CH', name: 'Switzerland' },
  { code: 'SE', name: 'Sweden' },
  { code: 'NO', name: 'Norway' },
  { code: 'FI', name: 'Finland' },
  { code: 'DK', name: 'Denmark' },
  { code: 'PT', name: 'Portugal' },
  { code: 'GR', name: 'Greece' },
  { code: 'RO', name: 'Romania' },
  { code: 'HU', name: 'Hungary' },
  { code: 'BE', name: 'Belgium' },
  { code: 'UZ', name: 'Uzbekistan' },
  { code: 'AZ', name: 'Azerbaijan' },
  { code: 'GE', name: 'Georgia' },
  { code: 'AM', name: 'Armenia' },
  { code: 'LV', name: 'Latvia' },
  { code: 'LT', name: 'Lithuania' },
  { code: 'EE', name: 'Estonia' },
  { code: 'MD', name: 'Moldova' },
  { code: 'KG', name: 'Kyrgyzstan' },
  { code: 'TJ', name: 'Tajikistan' },
  { code: 'TM', name: 'Turkmenistan' },
  // Additional common
  { code: 'CO', name: 'Colombia' },
  { code: 'PE', name: 'Peru' },
  { code: 'CL', name: 'Chile' },
  { code: 'PK', name: 'Pakistan' },
  { code: 'BD', name: 'Bangladesh' },
  { code: 'IR', name: 'Iran' },
  { code: 'IQ', name: 'Iraq' },
  { code: 'TW', name: 'Taiwan' },
  { code: 'HK', name: 'Hong Kong' },
  { code: 'NZ', name: 'New Zealand' },
].sort((a, b) => a.name.localeCompare(b.name));

/**
 * Curated cities — canonical names for consistent search.
 * Matches cityToCountryCode in lib/flag.ts where applicable.
 */
export const CITIES: string[] = [
  // Russia
  'Moscow',
  'Saint Petersburg',
  'Novosibirsk',
  'Yekaterinburg',
  'Kazan',
  'Nizhny Novgorod',
  'Samara',
  'Rostov-on-Don',
  'Krasnoyarsk',
  'Omsk',
  'Vladivostok',
  'Voronezh',
  'Krasnodar',
  'Saratov',
  'Tolyatti',
  // Kazakhstan
  'Almaty',
  'Astana',
  'Shymkent',
  'Karaganda',
  'Aktobe',
  'Taraz',
  // Ukraine
  'Kyiv',
  'Kharkiv',
  'Odesa',
  'Dnipro',
  'Lviv',
  // Belarus
  'Minsk',
  'Gomel',
  'Mogilev',
  // Europe
  'London',
  'Berlin',
  'Paris',
  'Amsterdam',
  'Madrid',
  'Rome',
  'Vienna',
  'Prague',
  'Warsaw',
  'Budapest',
  'Bucharest',
  'Athens',
  'Lisbon',
  'Brussels',
  'Zurich',
  'Stockholm',
  'Oslo',
  'Copenhagen',
  'Helsinki',
  'Dublin',
  'Istanbul',
  'Milan',
  'Barcelona',
  'Munich',
  'Hamburg',
  'Cologne',
  'Frankfurt',
  'Riga',
  'Tallinn',
  'Vilnius',
  'Chisinau',
  'Tbilisi',
  'Yerevan',
  'Baku',
  // Americas
  'New York',
  'Los Angeles',
  'Chicago',
  'Houston',
  'San Francisco',
  'Miami',
  'Boston',
  'Seattle',
  'Toronto',
  'Vancouver',
  'Montreal',
  'Mexico City',
  'São Paulo',
  'Rio de Janeiro',
  'Buenos Aires',
  'Bogotá',
  'Lima',
  'Santiago',
  'Caracas',
  // Asia
  'Tokyo',
  'Seoul',
  'Singapore',
  'Hong Kong',
  'Shanghai',
  'Beijing',
  'Taipei',
  'Bangkok',
  'Jakarta',
  'Kuala Lumpur',
  'Manila',
  'Ho Chi Minh City',
  'Mumbai',
  'Delhi',
  'Dubai',
  'Riyadh',
  'Tel Aviv',
  'Tashkent',
  'Bishkek',
  'Dushanbe',
  'Ashgabat',
  // Africa
  'Cairo',
  'Lagos',
  'Johannesburg',
  'Nairobi',
  'Casablanca',
  // Oceania
  'Sydney',
  'Melbourne',
  'Auckland',
].filter((v, i, a) => a.indexOf(v) === i) // dedupe
  .sort((a, b) => a.localeCompare(b, undefined, { sensitivity: 'base' }));
