/**
 * Curated lists for city and country dropdowns.
 * Single source of truth — used by extension, Discover, and API.
 */

export const COUNTRIES: { code: string; name: string }[] = [
  { code: 'RU', name: 'Russia' },
  { code: 'KZ', name: 'Kazakhstan' },
  { code: 'UA', name: 'Ukraine' },
  { code: 'BY', name: 'Belarus' },
  { code: 'US', name: 'United States' },
  { code: 'GB', name: 'United Kingdom' },
  { code: 'DE', name: 'Germany' },
  { code: 'FR', name: 'France' },
  { code: 'NL', name: 'Netherlands' },
  { code: 'PL', name: 'Poland' },
  { code: 'IT', name: 'Italy' },
  { code: 'ES', name: 'Spain' },
  { code: 'TR', name: 'Turkey' },
  { code: 'CA', name: 'Canada' },
  { code: 'AU', name: 'Australia' },
  { code: 'BR', name: 'Brazil' },
  { code: 'MX', name: 'Mexico' },
  { code: 'AR', name: 'Argentina' },
  { code: 'IN', name: 'India' },
  { code: 'CN', name: 'China' },
  { code: 'JP', name: 'Japan' },
  { code: 'KR', name: 'South Korea' },
  { code: 'SG', name: 'Singapore' },
  { code: 'ID', name: 'Indonesia' },
  { code: 'TH', name: 'Thailand' },
  { code: 'VN', name: 'Vietnam' },
  { code: 'PH', name: 'Philippines' },
  { code: 'MY', name: 'Malaysia' },
  { code: 'AE', name: 'United Arab Emirates' },
  { code: 'SA', name: 'Saudi Arabia' },
  { code: 'IL', name: 'Israel' },
  { code: 'EG', name: 'Egypt' },
  { code: 'ZA', name: 'South Africa' },
  { code: 'NG', name: 'Nigeria' },
  { code: 'KE', name: 'Kenya' },
  { code: 'CZ', name: 'Czech Republic' },
  { code: 'AT', name: 'Austria' },
  { code: 'CH', name: 'Switzerland' },
  { code: 'SE', name: 'Sweden' },
  { code: 'NO', name: 'Norway' },
  { code: 'FI', name: 'Finland' },
  { code: 'DK', name: 'Denmark' },
  { code: 'PT', name: 'Portugal' },
  { code: 'GR', name: 'Greece' },
  { code: 'RO', name: 'Romania' },
  { code: 'HU', name: 'Hungary' },
  { code: 'BE', name: 'Belgium' },
  { code: 'UZ', name: 'Uzbekistan' },
  { code: 'AZ', name: 'Azerbaijan' },
  { code: 'GE', name: 'Georgia' },
  { code: 'AM', name: 'Armenia' },
  { code: 'LV', name: 'Latvia' },
  { code: 'LT', name: 'Lithuania' },
  { code: 'EE', name: 'Estonia' },
  { code: 'MD', name: 'Moldova' },
  { code: 'KG', name: 'Kyrgyzstan' },
  { code: 'TJ', name: 'Tajikistan' },
  { code: 'TM', name: 'Turkmenistan' },
  // Additional common
  { code: 'CO', name: 'Colombia' },
  { code: 'PE', name: 'Peru' },
  { code: 'CL', name: 'Chile' },
  { code: 'PK', name: 'Pakistan' },
  { code: 'BD', name: 'Bangladesh' },
  { code: 'IR', name: 'Iran' },
  { code: 'IQ', name: 'Iraq' },
  { code: 'TW', name: 'Taiwan' },
  { code: 'HK', name: 'Hong Kong' },
  { code: 'NZ', name: 'New Zealand' },
].sort((a, b) => a.name.localeCompare(b.name));

/**
 * Cities by country code — for dependent dropdown (country → city).
 */
export const CITIES_BY_COUNTRY: Record<string, string[]> = {
  RU: ['Moscow', 'Saint Petersburg', 'Novosibirsk', 'Yekaterinburg', 'Kazan', 'Nizhny Novgorod', 'Samara', 'Rostov-on-Don', 'Krasnoyarsk', 'Omsk', 'Vladivostok', 'Voronezh', 'Krasnodar', 'Saratov', 'Tolyatti'],
  KZ: ['Almaty', 'Astana', 'Shymkent', 'Karaganda', 'Aktobe', 'Taraz'],
  UA: ['Kyiv', 'Kharkiv', 'Odesa', 'Dnipro', 'Lviv'],
  BY: ['Minsk', 'Gomel', 'Mogilev'],
  US: ['New York', 'Los Angeles', 'Chicago', 'Houston', 'San Francisco', 'Miami', 'Boston', 'Seattle'],
  GB: ['London'],
  DE: ['Berlin', 'Munich', 'Hamburg', 'Cologne', 'Frankfurt'],
  FR: ['Paris'],
  NL: ['Amsterdam'],
  PL: ['Warsaw'],
  IT: ['Rome', 'Milan'],
  ES: ['Madrid', 'Barcelona'],
  TR: ['Istanbul'],
  CA: ['Toronto', 'Vancouver', 'Montreal'],
  AU: ['Sydney', 'Melbourne'],
  BR: ['São Paulo', 'Rio de Janeiro'],
  MX: ['Mexico City'],
  AR: ['Buenos Aires'],
  IN: ['Mumbai', 'Delhi'],
  CN: ['Shanghai', 'Beijing'],
  JP: ['Tokyo'],
  KR: ['Seoul'],
  SG: ['Singapore'],
  ID: ['Jakarta'],
  TH: ['Bangkok'],
  VN: ['Ho Chi Minh City'],
  PH: ['Manila'],
  MY: ['Kuala Lumpur'],
  AE: ['Dubai'],
  SA: ['Riyadh'],
  IL: ['Tel Aviv'],
  EG: ['Cairo'],
  ZA: ['Johannesburg'],
  NG: ['Lagos'],
  KE: ['Nairobi'],
  CZ: ['Prague'],
  AT: ['Vienna'],
  CH: ['Zurich'],
  SE: ['Stockholm'],
  NO: ['Oslo'],
  FI: ['Helsinki'],
  DK: ['Copenhagen'],
  PT: ['Lisbon'],
  GR: ['Athens'],
  RO: ['Bucharest'],
  HU: ['Budapest'],
  BE: ['Brussels'],
  UZ: ['Tashkent'],
  AZ: ['Baku'],
  GE: ['Tbilisi'],
  AM: ['Yerevan'],
  LV: ['Riga'],
  LT: ['Vilnius'],
  EE: ['Tallinn'],
  MD: ['Chisinau'],
  KG: ['Bishkek'],
  TJ: ['Dushanbe'],
  TM: ['Ashgabat'],
  CO: ['Bogotá'],
  PE: ['Lima'],
  CL: ['Santiago'],
  IR: ['Tehran'],
  IQ: ['Baghdad'],
  TW: ['Taipei'],
  HK: ['Hong Kong'],
  NZ: ['Auckland'],
  MA: ['Casablanca'],
};

/**
 * All cities (flat) — for Discover when no country filter.
 */
export const CITIES: string[] = Object.values(CITIES_BY_COUNTRY)
  .flat()
  .filter((v, i, a) => a.indexOf(v) === i)
  .sort((a, b) => a.localeCompare(b, undefined, { sensitivity: 'base' }));

